
spring:
  application:
    name: financial
  datasource:
    url: jdbc:mysql://rm-6we8u0l05o7z6tf76jo.mysql.japan.rds.aliyuncs.com:3306/financial?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: financial
    password: "@tianli123456TL"
  redis:
    host: r-6wes3xh85wv4t8xp2jpd.redis.japan.rds.aliyuncs.com
    database: 56
    password: "@tianli123456TL"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true



# cookie age
cookie:
  age: 86400

# line login
line:
  client_id: 1655782165
  client_secret: 2b40fb5fef8648ad452933d9d5b520d4
  redirect_uri: /api/empty/callback
  host: https://api.line.me
  token_path: /oauth2/v2.1/token
  verify_path: /oauth2/v2.1/verify
  user_profile_path: /v2/profile

# facebook login
facebook:
  client_id: 494055761612981
  client_secret: 2aa46e159cadc29ba1aeb377b1b5f676
  redirect_uri: /api/empty/callback
  host: https://graph.facebook.com
  me_path: /v10.0/me
  debug_token_path: /v10.0/debug_token

email:
  amazon:
    accessKeyId: AKIAZYZHBHKS6FCP3Y7H
    secretAccessKey: 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

secret:
  ecdsa:
    privateKey: "e0906baea99bf1cec33b54d9041b9b90da524da501a470be4e35de0b5adac4a0"
# 1cb2398368a615bfe5a9685dece946eeb1bec2e7b9f1b76a88c5f893404dc18b91f3eff072e460a3ee8aa2e1d00051050abbadfa42d5c3592a65d9391bfbee29
mybatis:
  mapper-locations: classpath:***/*/*.xml
