# This is a basic workflow to help you get started with Actions

name: financial

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - uses: kciter/aws-ecr-action@master
        with:
          access_key_id: AKIARJZQDAVKKTS7CEXL
          secret_access_key: "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"
          account_id: "089758303572"
          repo: financial
          region: ap-northeast-1
          tags: latest
          create_repo: true
          dockerfile: Dockerfile-local
      - name: redeploy
        run: curl http://a77e44e0c66a143bda782dc0cdaea30b-69016204.ap-northeast-1.elb.amazonaws.com/6FGS959U9epLIJ6crvu4l2TsdpD4Ozyz2M7JEravear/default/financial
